const canvas = document.querySelector('#arena-canvas');
const ctx = canvas.getContext('2d');
const keys = new Set();
const skinColors = { solar: ['#f9dc62', '#ee7241'], ember: ['#ff8957', '#ad294d'], frost: ['#a9f8ff', '#3596c9'], void: ['#d1b6ff', '#7046d7'], toxic: ['#b5f34a', '#398b6b'], royal: ['#ff9fe7', '#743d91'] };
const maps = {
  'neon-yard': { name: 'Neon Yard', background: '#112a36', accent: '#64dbdd', obstacles: [{ x: 86, y: 80, w: 160, h: 82 }, { x: 716, y: 92, w: 140, h: 118 }, { x: 360, y: 366, w: 194, h: 84 }, { x: 430, y: 100, w: 80, h: 50 }] },
  'crystal-caves': { name: 'Crystal Caves', background: '#1b203b', accent: '#a9f8ff', obstacles: [{ x: 95, y: 92, w: 92, h: 158 }, { x: 250, y: 370, w: 135, h: 64 }, { x: 625, y: 80, w: 190, h: 70 }, { x: 700, y: 330, w: 104, h: 150 }] },
  'sky-platform': { name: 'Sky Platform', background: '#263047', accent: '#f4ca57', obstacles: [{ x: 100, y: 190, w: 190, h: 58 }, { x: 350, y: 90, w: 80, h: 148 }, { x: 570, y: 360, w: 220, h: 58 }, { x: 720, y: 100, w: 72, h: 130 }] },
  'mega-city': { name: 'Mega City', background: '#101d2d', accent: '#ff9fe7', obstacles: [{ x: 160, y: 140, w: 360, h: 120 }, { x: 720, y: 90, w: 240, h: 240 }, { x: 1180, y: 180, w: 420, h: 110 }, { x: 1810, y: 120, w: 330, h: 250 }, { x: 260, y: 620, w: 250, h: 310 }, { x: 730, y: 700, w: 440, h: 150 }, { x: 1370, y: 570, w: 210, h: 330 }, { x: 1780, y: 720, w: 400, h: 170 }, { x: 1040, y: 1040, w: 390, h: 160 }] }
};
const botNames = ['Vex', 'Kairo', 'Mira', 'Bolt', 'Rift'];
const botColors = ['#ff5964', '#57d8ec', '#d77aff', '#f4ca57', '#58e4a7'];
const worldSize = () => mode === 'mega' ? { width: 2400, height: 1400 } : { width: canvas.width, height: canvas.height };
let mode = 'brawl'; let skin = 'solar'; let armor = 'scout'; let power = 'blink'; let playerName = 'Nova'; let mapKey = 'neon-yard'; let playerCount = 3; let lastTime = 0; let matchSeconds = 180; let matchDuration = 180;
let score = 2450; let coins = 120; let gems = 8; let player; let enemies = []; let pickups = []; let particles = []; let gameOver = false; let challengeReady = false; let ttt = []; let weapon = 'pulse'; let crateInventory = 0; let matchStarted = false; const savedStats = JSON.parse(localStorage.getItem('arcade-arena-stats') || '{}'); const stats = { matches: savedStats.matches || 0, wins: savedStats.wins || 0, eliminations: savedStats.eliminations || 0, deaths: savedStats.deaths || 0, playTime: savedStats.playTime || 0 }; const ownedSkins = new Set(['solar']); const ownedWeapons = new Set(['pulse']); const ownedArmors = new Set(['scout']);
const armorStats = { scout: 0, titan: 30, aegis: 20, phase: 10 };
const armorProtection = { scout: 0, titan: .18, aegis: .28, phase: .12 };
const powerNames = { blink: 'Phase Blink', superjump: 'Super Jump', oneshot: 'One Shot', gravity: 'Gravity Well' };
const ultimateRewards = [{ type: 'SUPER POWER', name: 'Gravity Well', power: 'gravity' }, { type: 'SUPER POWER', name: 'Super Jump', power: 'superjump' }, { type: 'SKIN', name: 'Void Walker', skin: 'void' }, { type: 'SKIN', name: 'Royal Glitch', skin: 'royal' }, { type: 'WEAPON', name: 'Nova Cannon', weapon: 'nova' }, { type: 'WEAPON', name: 'Railgun X', weapon: 'railgun' }, { type: 'ARMOR', name: 'Aegis Core', armor: 'aegis' }, { type: 'ARCADE COINS', name: '250 Arcade Coins', coins: 250 }, { type: 'PREMIUM GEMS', name: '5 Premium Gems', gems: 5 }];

function resetGame() {
  const playerSpawn = findSpawn({ x: 270, y: 290 }, 17);
  const maxHp = 100 + armorStats[armor];
  player = { x: playerSpawn.x, y: playerSpawn.y, hp: maxHp, maxHp, radius: 17, cooldown: 0, abilityCooldown: 0, oneShotReady: false, flash: 0, kills: 0, alive: true, respawnTimer: 0, invulnerable: 1, name: playerName, color: skinColors[skin][0] };
  const starts = [{ x: 730, y: 145 }, { x: 730, y: 420 }, { x: 515, y: 500 }, { x: 140, y: 430 }, { x: 850, y: 300 }];
  enemies = Array.from({ length: playerCount - 1 }, (_, index) => { const spawn = findSpawn(starts[index], 18); return { x: spawn.x, y: spawn.y, hp: 100, radius: 18, kills: 0, color: botColors[index % botColors.length], name: `${botNames[index % botNames.length]} ${index + 1}`, cooldown: 1 + (index % 5) * .5, dir: index % 2 ? -1 : 1, alive: true, respawnTimer: 0, invulnerable: 1 }; });
  pickups = []; particles = []; matchSeconds = matchDuration; score = 2450; challengeReady = false; gameOver = false; ttt = ['', '', '', '', '', '', '', '', ''];
  document.querySelector('#match-result').classList.add('hidden'); document.querySelector('#match-label').textContent = 'MATCH IN PROGRESS'; renderChallenge(); updateHud(); updateShop();
}
function aliveCount() { return enemies.filter(enemy => enemy.alive).length + (player.alive ? 1 : 0); }
function formatTime(seconds) { return `${String(Math.floor(seconds / 60)).padStart(2, '0')}:${String(Math.max(0, Math.floor(seconds % 60))).padStart(2, '0')}`; }
function updateHud() {
  document.querySelector('#score-value').textContent = score.toLocaleString('en-US'); document.querySelector('#coin-value').textContent = coins; document.querySelector('#gem-value').textContent = gems; document.querySelector('#wallet-coins').textContent = coins; document.querySelector('#wallet-gems').textContent = gems; document.querySelector('#shop-coins').textContent = coins; document.querySelector('#shop-gems').textContent = gems; document.querySelector('#home-coins').textContent = coins; document.querySelector('#home-gems').textContent = gems; document.querySelector('#crate-count').textContent = `${crateInventory} CRATES`; document.querySelector('#open-crate').disabled = !crateInventory; document.querySelector('#vault-crate-count').textContent = `${crateInventory} crates ready`;
  document.querySelector('#player-hp').style.width = `${Math.max(0, player.hp / player.maxHp * 100)}%`; document.querySelector('#hp-copy').textContent = Math.max(0, Math.ceil(player.hp)); document.querySelector('#timer').textContent = formatTime(matchSeconds); document.querySelector('#side-timer').textContent = formatTime(matchSeconds); const ability = document.querySelector('#ability-power'); if (ability) ability.textContent = player.oneShotReady ? 'ONE SHOT READY' : `${powerNames[power]} · ${player.abilityCooldown > 0 ? Math.ceil(player.abilityCooldown) + 's' : 'Q READY'}`;
  const countText = `◉ ${aliveCount()} / ${playerCount}`; document.querySelector('#arena-player-count').textContent = countText; document.querySelector('#players-stat').textContent = `${aliveCount()} / ${playerCount}`; updateAnalytics();
}
function updateAnalytics() { const cards = document.querySelectorAll('#profile-view .analytics-grid > div'); if (cards.length < 4) return; cards[0].querySelector('b').textContent = stats.wins; cards[1].querySelector('b').textContent = `${stats.matches ? Math.round(stats.wins / stats.matches * 100) : 0}%`; cards[2].querySelector('b').textContent = stats.eliminations; cards[3].querySelector('b').textContent = `${Math.floor(stats.playTime / 60)}m`; localStorage.setItem('arcade-arena-stats', JSON.stringify(stats)); }
function spawnBurst(x, y, color, amount = 10) { for (let i = 0; i < amount; i++) particles.push({ x, y, vx: (Math.random() - .5) * 130, vy: (Math.random() - .5) * 130, life: .55, color }); }
function isBlocked(x, y, radius = 0) { return maps[mapKey].obstacles.some(obstacle => x + radius > obstacle.x && x - radius < obstacle.x + obstacle.w && y + radius > obstacle.y && y - radius < obstacle.y + obstacle.h); }
function findSpawn(preferred, radius) { const size = worldSize(); if (preferred && !isBlocked(preferred.x, preferred.y, radius)) return preferred; for (let attempt = 0; attempt < 80; attempt++) { const x = 40 + Math.random() * (size.width - 80); const y = 40 + Math.random() * (size.height - 80); if (!isBlocked(x, y, radius)) return { x, y }; } for (let y = 40; y < size.height - 40; y += 32) for (let x = 40; x < size.width - 40; x += 32) if (!isBlocked(x, y, radius)) return { x, y }; return { x: 40, y: 40 }; }
function respawnEntity(entity, delta) { if (entity.alive) return; entity.respawnTimer -= delta; if (entity.respawnTimer > 0) return; const spawn = findSpawn(null, entity.radius); entity.x = spawn.x; entity.y = spawn.y; entity.hp = entity === player ? player.maxHp : 100; entity.alive = true; entity.invulnerable = 1.4; entity.cooldown = 1.5; }
function moveWithWalls(entity, dx, dy) { const size = worldSize(); const nextX = Math.max(27, Math.min(size.width - 27, entity.x + dx)); const nextY = Math.max(27, Math.min(size.height - 27, entity.y + dy)); if (!isBlocked(nextX, entity.y, entity.radius)) entity.x = nextX; if (!isBlocked(entity.x, nextY, entity.radius)) entity.y = nextY; }
function dropLoot(x, y, killer) { const type = Math.random() > .78 ? 'gem' : 'coin'; pickups.push({ x, y, type, claimed: false }); if (killer === player) score += 100; }
function eliminate(target, killer) {
  if (!target.alive) return; target.alive = false; target.hp = 0; target.respawnTimer = 2.2; spawnBurst(target.x, target.y, target.color, 22); dropLoot(target.x, target.y, killer);
  if (killer && typeof killer.kills === 'number') killer.kills++;
  if (killer === player) { stats.eliminations++; score += 500; challengeReady = true; document.querySelector('#match-label').textContent = mode === 'tictactoe' ? 'ELIMINATION: ONE GRID TRY' : 'ELIMINATION +500'; renderChallenge(); }
  if (target === player) stats.deaths++;
}
function attack() {
  if (gameOver || !player.alive || player.cooldown > 0) return; player.cooldown = .38; player.flash = .12;
  const target = enemies.filter(enemy => enemy.alive).find(enemy => Math.hypot(enemy.x - player.x, enemy.y - player.y) < 145 && !isBlocked((enemy.x + player.x) / 2, (enemy.y + player.y) / 2));
  if (target) { const weaponDamage = { pulse: 48, scatter: 70, lance: 92, railgun: 130, nova: 160 }; const damage = weaponDamage[weapon] * (player.oneShotReady ? 3 : 1); player.oneShotReady = false; target.hp -= damage; spawnBurst(target.x, target.y, skinColors[skin][0], 5); if (target.hp <= 0) eliminate(target, player); }
}
function activatePower() { if (gameOver || !player.alive || player.abilityCooldown > 0) return; const dx = (keys.has('d') || keys.has('arrowright') ? 1 : 0) - (keys.has('a') || keys.has('arrowleft') ? 1 : 0); const dy = (keys.has('s') || keys.has('arrowdown') ? 1 : 0) - (keys.has('w') || keys.has('arrowup') ? 1 : 0); const length = Math.hypot(dx, dy) || 1; if (power === 'oneshot') player.oneShotReady = true; if (power === 'blink' || power === 'superjump') { moveWithWalls(player, (dx || 1) / length * (power === 'superjump' ? 260 : 170), (dy || 0) / length * (power === 'superjump' ? 260 : 170)); player.invulnerable = power === 'superjump' ? 1.2 : .7; spawnBurst(player.x, player.y, skinColors[skin][0], 18); } if (power === 'gravity') { enemies.filter(enemy => enemy.alive && Math.hypot(enemy.x - player.x, enemy.y - player.y) < 190).forEach(enemy => { enemy.hp -= 40; if (enemy.hp <= 0) eliminate(enemy, player); }); spawnBurst(player.x, player.y, '#b88cff', 28); } player.abilityCooldown = 6; }
function nearestTarget(enemy) { return [player, ...enemies].filter(target => target !== enemy && target.alive).sort((a, b) => Math.hypot(a.x - enemy.x, a.y - enemy.y) - Math.hypot(b.x - enemy.x, b.y - enemy.y))[0]; }
function updateEnemy(enemy, delta) {
  if (!enemy.alive) return; const target = nearestTarget(enemy); if (!target) return; const dx = target.x - enemy.x; const dy = target.y - enemy.y; const dist = Math.hypot(dx, dy); if (dist > 105) moveWithWalls(enemy, dx / dist * 34 * delta * enemy.dir, dy / dist * 34 * delta); enemy.cooldown -= delta; enemy.invulnerable = Math.max(0, enemy.invulnerable - delta);
  if (dist < 88 && enemy.cooldown <= 0 && !target.invulnerable) { target.hp -= target === player ? 8 * (1 - armorProtection[armor]) : 18; enemy.cooldown = 1.25; spawnBurst(target.x, target.y, enemy.color, 4); if (target.hp <= 0) eliminate(target, enemy); }
}
function collectPickups() { pickups.forEach(pickup => { if (!pickup.claimed && Math.hypot(pickup.x - player.x, pickup.y - player.y) < 28) { pickup.claimed = true; if (pickup.type === 'coin') { coins++; score += 75; } else { gems++; score += 250; } spawnBurst(pickup.x, pickup.y, pickup.type === 'coin' ? '#f4ca57' : '#57d8ec', 9); } }); pickups = pickups.filter(pickup => !pickup.claimed); }
function movePlayer(delta) { const dx = (keys.has('d') || keys.has('arrowright') ? 1 : 0) - (keys.has('a') || keys.has('arrowleft') ? 1 : 0); const dy = (keys.has('s') || keys.has('arrowdown') ? 1 : 0) - (keys.has('w') || keys.has('arrowup') ? 1 : 0); if (dx || dy) { const length = Math.hypot(dx, dy); moveWithWalls(player, dx / length * 220 * delta, dy / length * 220 * delta); } }
function update(delta) { if (gameOver) return; if (matchStarted) stats.playTime += delta; matchSeconds = Math.max(0, matchSeconds - delta); if (!matchSeconds) finishMatch(); if (player.alive) movePlayer(delta); player.cooldown = Math.max(0, player.cooldown - delta); player.abilityCooldown = Math.max(0, player.abilityCooldown - delta); player.flash = Math.max(0, player.flash - delta); player.invulnerable = Math.max(0, player.invulnerable - delta); if (!player.alive) respawnEntity(player, delta); enemies.forEach(enemy => { if (!enemy.alive) respawnEntity(enemy, delta); else updateEnemy(enemy, delta); }); collectPickups(); particles.forEach(p => { p.x += p.vx * delta; p.y += p.vy * delta; p.life -= delta; }); particles = particles.filter(p => p.life > 0); updateHud(); }
function drawArena() {
  const currentMap = maps[mapKey]; const size = worldSize(); const cameraX = mode === 'mega' ? Math.max(0, Math.min(size.width - canvas.width, player.x - canvas.width / 2)) : 0; const cameraY = mode === 'mega' ? Math.max(0, Math.min(size.height - canvas.height, player.y - canvas.height / 2)) : 0;
  ctx.clearRect(0, 0, canvas.width, canvas.height); ctx.fillStyle = currentMap.background; ctx.fillRect(0, 0, canvas.width, canvas.height); ctx.save(); ctx.translate(-cameraX, -cameraY); ctx.strokeStyle = `${currentMap.accent}18`; ctx.lineWidth = 1;
  for (let x = 0; x < size.width; x += 40) { ctx.beginPath(); ctx.moveTo(x, 0); ctx.lineTo(x, size.height); ctx.stroke(); } for (let y = 0; y < size.height; y += 40) { ctx.beginPath(); ctx.moveTo(0, y); ctx.lineTo(size.width, y); ctx.stroke(); }
  currentMap.obstacles.forEach(obstacle => { ctx.fillStyle = '#0a1522'; ctx.fillRect(obstacle.x, obstacle.y, obstacle.w, obstacle.h); ctx.strokeStyle = `${currentMap.accent}66`; ctx.strokeRect(obstacle.x, obstacle.y, obstacle.w, obstacle.h); ctx.fillStyle = `${currentMap.accent}20`; ctx.fillRect(obstacle.x + 7, obstacle.y + 7, obstacle.w - 14, 4); });
  ctx.fillStyle = `${currentMap.accent}18`; ctx.beginPath(); ctx.arc(size.width / 2, size.height / 2, 120, 0, Math.PI * 2); ctx.fill(); pickups.forEach(drawPickup); particles.forEach(p => { ctx.globalAlpha = Math.max(0, p.life * 1.8); ctx.fillStyle = p.color; ctx.fillRect(p.x, p.y, 4, 4); }); ctx.globalAlpha = 1; enemies.forEach(enemy => { if (enemy.alive) drawEnemy(enemy); }); if (player.alive) drawPlayer(); ctx.restore();
}
function drawPickup(pickup) { ctx.save(); ctx.translate(pickup.x, pickup.y); ctx.shadowBlur = 15; ctx.shadowColor = pickup.type === 'coin' ? '#f4ca57' : '#57d8ec'; ctx.fillStyle = pickup.type === 'coin' ? '#f4ca57' : '#57d8ec'; ctx.rotate(Math.PI / 4); ctx.fillRect(-7, -7, 14, 14); ctx.restore(); }
function drawPlayer() { const [bright, dark] = skinColors[skin]; ctx.save(); ctx.translate(player.x, player.y); if (armor !== 'scout') { ctx.strokeStyle = `#b88cff${Math.round((.35 + armorProtection[armor]) * 255).toString(16).padStart(2, '0')}`; ctx.lineWidth = 4; ctx.shadowColor = '#b88cff'; ctx.shadowBlur = 14; ctx.beginPath(); ctx.arc(0, 0, player.radius + 9, 0, Math.PI * 2); ctx.stroke(); } ctx.shadowColor = bright; ctx.shadowBlur = player.flash ? 28 : 13; ctx.fillStyle = dark; ctx.beginPath(); ctx.arc(0, 0, player.radius + 4, 0, Math.PI * 2); ctx.fill(); ctx.fillStyle = bright; ctx.beginPath(); ctx.arc(0, 0, player.radius, 0, Math.PI * 2); ctx.fill(); ctx.fillStyle = '#17202b'; ctx.beginPath(); ctx.arc(-5, -3, 3, 0, Math.PI * 2); ctx.arc(6, -3, 3, 0, Math.PI * 2); ctx.fill(); ctx.fillStyle = '#fff3b0'; ctx.fillRect(-8, 8, 16, 2); ctx.restore(); label(player.x, player.y + 34, player.name, bright); }
function drawEnemy(enemy) { ctx.save(); ctx.translate(enemy.x, enemy.y); ctx.shadowColor = enemy.color; ctx.shadowBlur = 13; ctx.fillStyle = enemy.color; ctx.beginPath(); ctx.moveTo(0, -enemy.radius - 4); ctx.lineTo(enemy.radius + 4, enemy.radius); ctx.lineTo(0, enemy.radius - 3); ctx.lineTo(-enemy.radius - 4, enemy.radius); ctx.closePath(); ctx.fill(); ctx.fillStyle = '#162230'; ctx.fillRect(-8, -1, 5, 5); ctx.fillRect(3, -1, 5, 5); ctx.restore(); ctx.fillStyle = '#24364a'; ctx.fillRect(enemy.x - 20, enemy.y - 34, 40, 4); ctx.fillStyle = enemy.color; ctx.fillRect(enemy.x - 20, enemy.y - 34, 40 * enemy.hp / 100, 4); label(enemy.x, enemy.y + 35, enemy.name, enemy.color); }
function label(x, y, text, color) { ctx.fillStyle = color; ctx.font = '700 10px Space Grotesk'; ctx.textAlign = 'center'; ctx.fillText(text, x, y); }
function frame(time) { const delta = Math.min(.04, (time - lastTime) / 1000 || 0); lastTime = time; update(delta); drawArena(); requestAnimationFrame(frame); }
function setMatchLock(active) { document.body.classList.toggle('match-active', active); document.querySelector('#arena-view').classList.toggle('match-locked', active); }
function finishMatch() { if (gameOver) return; gameOver = true; const standings = [player, ...enemies].sort((first, second) => second.kills - first.kills); const winner = standings[0]; const playerWon = winner === player; if (matchStarted) { stats.matches++; if (playerWon) stats.wins++; } if (playerWon) { crateInventory++; score += 500; document.querySelector('#ultimate-copy').textContent = 'Ottelu päättyi. Arcade Ultimate lisättiin tilillesi.'; } const result = document.querySelector('#match-result'); document.querySelector('#result-title').textContent = playerWon ? 'VICTORY' : `${winner.name.toUpperCase()} WINS`; document.querySelector('#result-copy').textContent = `${winner.name} voitti ${winner.kills} eliminaatiolla.${playerWon ? ' Arcade Ultimate lisätty tilillesi.' : ' Kerää enemmän eliminaatioita seuraavassa matsissa.'}`; let scoreboard = document.querySelector('#match-scoreboard'); if (!scoreboard) { scoreboard = document.createElement('div'); scoreboard.id = 'match-scoreboard'; result.insertBefore(scoreboard, document.querySelector('#rematch-button')); } scoreboard.innerHTML = standings.slice(0, 8).map((entry, index) => `<div><span>${String(index + 1).padStart(2, '0')}</span><b>${entry.name}</b><strong>${entry.kills} KOs</strong></div>`).join(''); let reward = document.querySelector('#match-reward'); if (!reward) { reward = document.createElement('div'); reward.id = 'match-reward'; result.insertBefore(reward, document.querySelector('#rematch-button')); } reward.textContent = playerWon ? `+1 ARCADE ULTIMATE · ${crateInventory} TILILLÄ` : 'NO ARCADE ULTIMATE THIS MATCH'; result.classList.remove('hidden'); setMatchLock(false); if (document.fullscreenElement) document.exitFullscreen().catch(() => {}); updateHud(); }
function renderChallenge() {
  const tttReady = mode === 'tictactoe' && challengeReady; document.querySelector('#ttt-streak').textContent = tttReady ? '1 TRY READY' : 'LOCKED'; document.querySelector('#ttt-instruction').textContent = tttReady ? 'Yksi yritys: valitse yksi ruutu.' : 'Eliminaatio avaa yhden ruutuyrityksen.'; renderTtt();
}
function renderTtt() { const board = document.querySelector('#ttt-board'); board.innerHTML = ''; ttt.forEach((value, index) => { const cell = document.createElement('button'); cell.className = `ttt-cell ${value === 'O' ? 'o' : ''}`; cell.textContent = value; cell.disabled = !challengeReady || Boolean(value) || mode !== 'tictactoe'; cell.addEventListener('click', () => makeTttMove(index)); board.appendChild(cell); }); document.querySelector('#ttt-status').textContent = challengeReady && mode === 'tictactoe' ? 'Yksi yritys: valitse yksi ruutu' : 'Odota omaa eliminaatiota'; }
function hasLine(mark) { return [[0, 1, 2], [3, 4, 5], [6, 7, 8], [0, 3, 6], [1, 4, 7], [2, 5, 8], [0, 4, 8], [2, 4, 6]].some(line => line.every(index => ttt[index] === mark)); }
function makeTttMove(index) { if (!challengeReady || ttt[index] || mode !== 'tictactoe') return; challengeReady = false; ttt[index] = 'X'; score += 100; if (hasLine('X')) { document.querySelector('#match-label').textContent = 'GRID CAPTURED · MINIGAME WON'; finishMatch(); } else { const empty = ttt.map((value, position) => value ? -1 : position).filter(position => position >= 0); if (empty.length) ttt[empty[Math.floor(Math.random() * empty.length)]] = 'O'; } renderChallenge(); updateHud(); }
function updateShop() { document.querySelectorAll('.skin-card').forEach(card => { const owned = ownedSkins.has(card.dataset.skin); card.classList.toggle('owned', owned); card.classList.toggle('selected', skin === card.dataset.skin); }); document.querySelectorAll('.weapon-card').forEach(card => { const owned = ownedWeapons.has(card.dataset.weapon); card.classList.toggle('owned', owned); card.classList.toggle('active', weapon === card.dataset.weapon); }); document.querySelectorAll('.armor-card').forEach(card => { const owned = ownedArmors.has(card.dataset.armor); card.classList.toggle('owned', owned); card.classList.toggle('active', armor === card.dataset.armor); }); }
function buyOrEquipSkin(card) { const skinId = card.dataset.skin; if (!ownedSkins.has(skinId)) { const price = Number(card.dataset.price); const gemPrice = card.dataset.gemPrice === 'true'; if (gemPrice ? gems < price : coins < price) { document.querySelector('#match-label').textContent = 'NOT ENOUGH CURRENCY'; return; } if (gemPrice) gems -= price; else coins -= price; ownedSkins.add(skinId); } skin = skinId; player.color = skinColors[skin][0]; updateShop(); updateHud(); }
function buyOrEquipWeapon(card) { const weaponId = card.dataset.weapon; if (!ownedWeapons.has(weaponId)) { const price = Number(card.dataset.price); const gemPrice = card.dataset.gemPrice === 'true'; if (gemPrice ? gems < price : coins < price) { document.querySelector('#match-label').textContent = 'NOT ENOUGH CURRENCY'; return; } if (gemPrice) gems -= price; else coins -= price; ownedWeapons.add(weaponId); } weapon = weaponId; updateShop(); updateHud(); }
function buyOrEquipArmor(card) { const armorId = card.dataset.armor; if (!ownedArmors.has(armorId)) { const price = Number(card.dataset.price); const gemPrice = card.dataset.gemPrice === 'true'; if (gemPrice ? gems < price : coins < price) { document.querySelector('#match-label').textContent = 'NOT ENOUGH CURRENCY'; return; } if (gemPrice) gems -= price; else coins -= price; ownedArmors.add(armorId); } armor = armorId; updateShop(); resetGame(); updateHud(); }
function openCrate() { if (!crateInventory) return; crateInventory--; const reward = ultimateRewards[Math.floor(Math.random() * ultimateRewards.length)]; if (reward.skin) ownedSkins.add(reward.skin); if (reward.weapon) ownedWeapons.add(reward.weapon); if (reward.armor) ownedArmors.add(reward.armor); if (reward.power) { power = reward.power; document.querySelectorAll('.power-card').forEach(card => card.classList.toggle('active', card.dataset.power === power)); } if (reward.coins) coins += reward.coins; if (reward.gems) gems += reward.gems; const modal = document.querySelector('.reward-modal'); let rewardType = document.querySelector('#reward-type'); if (!rewardType) { rewardType = document.createElement('small'); rewardType.id = 'reward-type'; modal.insertBefore(rewardType, document.querySelector('#reward-name')); } const rewardCopy = document.querySelector('.reward-modal p'); rewardCopy.id = 'reward-copy'; document.querySelector('#ultimate-name').textContent = reward.name; document.querySelector('#ultimate-copy').textContent = `${reward.type} lisätty tilillesi.`; document.querySelector('#open-crate').textContent = 'ULTIMATE READY'; document.querySelector('#crate-history').textContent = `Unlocked ${reward.type}: ${reward.name}`; rewardType.textContent = reward.type; document.querySelector('#reward-name').textContent = reward.name; rewardCopy.textContent = reward.power ? 'Supervoima on valittu käyttöön.' : 'Palkinto on lisätty tilillesi.'; document.querySelector('#crate-overlay').classList.remove('hidden'); updateShop(); updateHud(); }
function buyCrate() { if (coins < 80) { document.querySelector('#match-label').textContent = 'NOT ENOUGH COINS'; return; } coins -= 80; crateInventory++; document.querySelector('#ultimate-copy').textContent = 'Ostit yllätyslaatikon. Avaa se Crates-valikosta.'; updateHud(); }
function startMatch() { mode = document.querySelector('#play-mode-select').value; mapKey = mode === 'mega' ? 'mega-city' : document.querySelector('#play-map-select').value; matchDuration = Number(document.querySelector('#play-time-select').value); playerCount = Number(document.querySelector('#play-player-select').value); selectMode(mode); matchStarted = true; resetGame(); showView('arena'); setMatchLock(true); if (document.documentElement.requestFullscreen) document.documentElement.requestFullscreen().catch(() => {}); }
function showView(view) { if (matchStarted && !gameOver && view !== 'arena') return; ['home', 'play', 'arena', 'loadout', 'shop', 'profile', 'crates', 'leaderboard'].forEach(name => document.querySelector(`#${name}-view`).classList.toggle('hidden', name !== view)); document.querySelectorAll('.nav-item[data-view]').forEach(nav => nav.classList.toggle('active', nav.dataset.view === view)); }
function selectMode(nextMode) { mode = nextMode; document.querySelectorAll('.mode-tab').forEach(tab => tab.classList.toggle('active', tab.dataset.mode === mode)); document.querySelector('#ttt-panel').classList.toggle('hidden', mode !== 'tictactoe'); const titles = { brawl: ['Brawl Royale', 'Fight, respawn and collect score until the timer ends.'], coinrush: ['Coin Rush', 'Collect coins and gems before the clock reaches zero.'], tictactoe: ['Tic tac takeover', 'Your eliminations unlock one grid move at a time.'], survival: ['Survival Swarm', 'Survive the waves and build the biggest elimination streak.'], capture: ['Crystal Capture', 'Control the glowing core to earn points for your team.'], bossrush: ['Boss Rush', 'Take down elite enemies before the timer runs out.'], mega: ['Mega Mode', '10, 30 or 50 brawlers. Choose a 5, 10 or 20 minute showdown.'] }; document.querySelector('#mode-title').textContent = titles[mode][0]; document.querySelector('#mode-copy').textContent = titles[mode][1]; renderChallenge(); }
function setPlayerCount(nextCount) { playerCount = nextCount; document.querySelectorAll('[data-players]').forEach(button => button.classList.toggle('active', Number(button.dataset.players) === playerCount)); resetGame(); }
function setMap(nextMap) { mapKey = nextMap; resetGame(); }
function ensurePowerLoadout() { const loadout = document.querySelector('#loadout-view'); if (!loadout.querySelector('.power-list')) { const powers = document.createElement('div'); powers.className = 'power-list'; powers.innerHTML = '<button class="power-card active" data-power="blink"><b>Q · Phase Blink</b><small>Teleport forward and dodge damage.</small></button><button class="power-card" data-power="superjump"><b>Q · Super Jump</b><small>Jump 260 units and become invulnerable.</small></button><button class="power-card" data-power="oneshot"><b>Q · One Shot</b><small>Next weapon hit deals 3x damage.</small></button><button class="power-card" data-power="gravity"><b>Q · Gravity Well</b><small>Damage nearby enemies.</small></button>'; loadout.insertBefore(powers, loadout.querySelector('.loadout-shop')); const note = document.createElement('div'); note.className = 'hotkey-note'; note.innerHTML = '<kbd>Q</kbd> ACTIVATE SELECTED POWER'; loadout.insertBefore(note, loadout.querySelector('.loadout-shop')); } const abilityBar = document.querySelector('.ability-bar'); if (abilityBar) abilityBar.innerHTML = '<span class="selected-power-key">Q</span><span id="ability-power">Phase Blink · Q READY</span><span class="ultimate">E <i>READY</i></span>'; }

document.addEventListener('keydown', event => { keys.add(event.key.toLowerCase()); if (event.code === 'Space') { event.preventDefault(); attack(); } if (event.key.toLowerCase() === 'r' && (!matchStarted || gameOver)) resetGame(); }); document.addEventListener('keyup', event => keys.delete(event.key.toLowerCase()));
ensurePowerLoadout(); document.querySelector('#crates-view .crate-vault small').textContent = 'Possible drops: Super Powers · Skins · Weapons · Armor · Coins · Gems'; document.querySelectorAll('.mode-tab').forEach(tab => tab.addEventListener('click', () => selectMode(tab.dataset.mode))); document.querySelectorAll('.skin-card').forEach(card => card.addEventListener('click', () => buyOrEquipSkin(card))); document.querySelectorAll('.weapon-card').forEach(card => card.addEventListener('click', () => buyOrEquipWeapon(card))); document.querySelectorAll('.armor-card').forEach(card => card.addEventListener('click', () => buyOrEquipArmor(card))); document.querySelectorAll('[data-players]').forEach(button => button.addEventListener('click', () => setPlayerCount(Number(button.dataset.players)))); document.querySelector('#map-select').addEventListener('change', event => setMap(event.target.value)); document.querySelector('#reset-match').addEventListener('click', resetGame); document.querySelector('#rematch-button').addEventListener('click', () => { matchStarted = true; resetGame(); setMatchLock(true); if (document.documentElement.requestFullscreen) document.documentElement.requestFullscreen().catch(() => {}); }); document.querySelector('#leave-match').addEventListener('click', () => finishMatch()); document.querySelector('#open-crate').addEventListener('click', openCrate); document.querySelector('#open-crate-menu').addEventListener('click', openCrate); document.querySelector('#buy-crate-menu').addEventListener('click', buyCrate); document.querySelector('#buy-crate-match').addEventListener('click', buyCrate); document.querySelector('#start-match').addEventListener('click', startMatch); document.querySelector('#save-name').addEventListener('click', saveName);
[['survival', 'Survival Swarm'], ['capture', 'Crystal Capture'], ['bossrush', 'Boss Rush']].forEach(([value, label]) => { const option = document.createElement('option'); option.value = value; option.textContent = label; document.querySelector('#play-mode-select').appendChild(option); });
document.querySelectorAll('.nav-item[data-view], [data-view]').forEach(item => item.addEventListener('click', () => showView(item.dataset.view))); document.querySelectorAll('.back-arena').forEach(button => button.addEventListener('click', () => showView('arena'))); document.querySelectorAll('.power-card').forEach(card => card.addEventListener('click', () => { power = card.dataset.power; document.querySelectorAll('.power-card').forEach(item => item.classList.toggle('active', item === card)); })); document.querySelector('#shop-buy-crate').addEventListener('click', buyCrate); document.querySelector('#shop-open-crates').addEventListener('click', () => showView('crates')); document.querySelector('#close-reward').addEventListener('click', () => document.querySelector('#crate-overlay').classList.add('hidden'));
document.addEventListener('keydown', event => { if (event.key.toLowerCase() === 'q') activatePower(); });
function saveName() { const nextName = document.querySelector('#name-input').value.trim().replace(/[^a-zA-Z0-9 _-]/g, '').slice(0, 14); if (!nextName) return; playerName = nextName; document.querySelector('#profile-name').textContent = playerName; document.querySelector('#home-name').textContent = playerName.toUpperCase(); document.querySelector('#profile-heading').textContent = playerName; document.querySelector('#name-input').value = playerName; document.querySelector('.team-status b').textContent = playerName; if (player) player.name = playerName; document.querySelector('#match-label').textContent = 'NAME UPDATED'; }
resetGame(); showView('home'); requestAnimationFrame(frame);
